# Generated by Django 4.2 on 2026-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate Phone Number (Optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer/Contact Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Primary Phone Number', max_length=20, null=True),
        ),
    ]
